import React, { useEffect } from 'react';

const Publications = () => {
  useEffect(() => {
    document.title = 'Publications - INHPC';
    const favicon = document.querySelector("link[rel='icon']");
    if (favicon) {
      favicon.href = '/logo.png';
    }
  }, []);

  return (
    <div className="content" style={{ maxWidth: '900px', margin: '0 auto', padding: '20px', textAlign: 'left' }}>
      <h1>著作</h1>

      <h2>Accepted Papers to be Published</h2>
      <ol>
        <li>Chia-Hung Lin and Sun-Yuan Hsieh "Improving the Search Mechanism for Unstructured Peer-to-Peer Networks Using the Statistical Matrix Form" IEEE Access, accepted.</li>
        <li>Limei Lin, Li Xu, Shuming Zhou, and Sun-Yuan Hsieh "The extra, restricted connectivity and conditional diagnosability of split-star networks" IEEE Transactions on Parallel and Distributed Systems, accepted. SCI EI</li>
        <li>Chia-Wen Cheng and Sun-Yuan Hsieh "Fault-tolerant cycle embedding in Cartesian product graphs: edge-pancyclicity and edge-bipancyclicity with faulty edges" IEEE Transactions on Parallel and Distributed Systems, accepted.SCI EI</li>
        <li>Chun-An Chen, Guey-Yun Chang, and Sun-Yuan Hsieh "Conditional (t,k)-diagnosis in graphs by using the comparison diagnosis model" IEEE Transactions on Computers, accepted. SCI EI</li>
        <li>Chia-Wei Lee and Sun-Yuan Hsieh "Diagnosability of Component-Composition Graphs in the MM* Model" ACM Transactions on Design Automation of Electronic Systems, accepted. SCI</li>
      </ol>

      <h2>Refereed Papers</h2>
      <ol>
        <li>Nai-Wen Chang, Wei-Hao Deng, and Sun-Yuan Hsieh "Conditional diagnosability of (n,k)-star networks under the comparison diagnosis model" IEEE Transactions on Reliability, vol. 64, no. 1, March 2015. SCI</li>
        <li>Nai-Wen Chang, Eddie Cheng, and Sun-Yuan Hsieh "Conditional diagnosability of Cayley graphs generated by transposition trees under the PMC model" ACM Transactions on Design Automation of Electronic Systems, vol. 20, no. 2, article 20, February 2015. SCI</li>
        <li>Chia-Wei Lee, Chao-Wen Huang, Wen-Hao Pi, and Sun-Yuan Hsieh "An improved approximation ratio to the partial-terminal Steiner tree problem" IEEE Transactions on Computers, vol. 64, no. 1, pp. 274-279, January 2015. SCI EI</li>
        <li>Chia-Wei Lee, Pin-Liang Chen, and Sun-Yuan Hsieh "Weight-constrained and density-constrained paths in a tree: enumerating, counting, and k-maximum density paths" Discrete Applied Mathematics, vol. 180, pp. 126-134, January 2015. SCI EI</li>
        <li>Nai-Wen Chang and Sun-Yuan Hsieh "Structural properties and conditional diagnosability of star graphs by using the PMC model" IEEE Transactions on Parallel and Distributed Systems, vol. 25, no. 11, pp. 3002-3011, November 2014. SCI EI</li>
      </ol>

      <h2>Conference Papers ── 國際會議</h2>
      <ol>
        <li>Chia-Wen Cheng and Sun-Yuan Hsieh "Bounds for the super extra edge connectivity of graphs" Proceedings of the 21th Annual International Computing and Combinatorics Conference (COCOON 2015, Beijing China), LNCS 9198, pp. 479-486, 2015.</li>
        <li>Sun-Yuan Hsieh, Chia-Wei Lee, Zong-Ying Yang, Heng-Wei Wang, and Jun-Han Yu "A Novel Algorithm for Classifying Protein Structure Familiar by Using the Graph Mining Approach" Proceedings of International Conference on Intelligent Computing (ICIC), Fuzhou, China, August 20-23, Lecture Notes in Computer Science, 2015.</li>
        <li>Sun-Yuan Hsieh, I-Pien Tsai, Hao-Che Hung, Yi-Chun Chen, Hsin-Hung Chou, and Chia-Wei Lee "An Enhanced Algorithm for Reconstructing a Phylogenetic Tree Based on the Tree Rearrangement and Maximum Likelihood Method" Proceedings of International Conference on Intelligent Computing (ICIC), Fuzhou, China, August 20-23, Lecture Notes in Computer Science 9226, 2015.</li>
        <li>Sun-Yuan Hsieh and Po-Cheng Hsu "A Novel Dynamic IP Router-table Design for Internet" Proceedings of International Conference on Computer and Information Sciences (ICCIS), Hong Kong SkyCity Marriott Hotel, 06 - 08 July 2015 (Best Paper Award).</li>
        <li>Chia-Wei Lee, Horng-Chyau Huang, and Sun-Yuan Hsieh "IDP: An Innovative Data Placement Algorithm for Hadoop Systems" Proceedings of International Computer Symposium (ICS2014 Dec. 12-14, Tunghai University, Taichung, Taiwan), vol. 1, pp. 47-56.</li>
      </ol>
    </div>
  );
};

export default Publications;
